// src/components/ui/Checkbox/Checkbox.tsx
import * as CheckboxPrimitive from "@radix-ui/react-checkbox";
import { Check } from "lucide-react"; // Icon check mặc định
import { cn } from "@/lib/utils";
import { forwardRef, ElementRef, ComponentPropsWithoutRef } from "react";

const Checkbox = forwardRef<
  ElementRef<typeof CheckboxPrimitive.Root>,
  ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root>
>(({ className, ...props }, ref) => (
  <CheckboxPrimitive.Root
    ref={ref}
    className={cn(
      "peer h-4 w-4 shrink-0 rounded-sm border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground",
      className
    )}
    {...props}
  >
    <CheckboxPrimitive.Indicator
      className={cn("flex items-center justify-center text-current")}
    >
      <Check className="h-4 w-4" />
    </CheckboxPrimitive.Indicator>
  </CheckboxPrimitive.Root>
));

Checkbox.displayName = CheckboxPrimitive.Root.displayName;

export { Checkbox };

// src/lib/components/ui/checkbox/checkbox.svelte
<script lang="ts">
  import { cn } from '$lib/utils/cn';

  export let checked: boolean | undefined = undefined;
  export let indeterminate = false;
  export let disabled = false;
  export let className = '';

  let element: HTMLInputElement | null = null;

  const baseClass =
    'h-4 w-4 rounded border-border text-primary focus:ring-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50';

  $: {
    if (element) {
      element.indeterminate = indeterminate;
    }
  }
</script>

<input
  bind:this={element}
  bind:checked
  class={cn(baseClass, className)}
  {disabled}
  type="checkbox"
  on:change
  on:keydown
  {...$$restProps}
/>
